### ISSUE TITLE
Error while retrieving the user profile

### ISSUE THREAD

**Issue by eugeniop** [xinbenlv/passport-renren#1]
I'm getting this error when the strategy calls `userProfile`:

> API1.0接口即将废弃，请使用最新API2.0接口

Maybe the endpoint has changed? or has been updated since then?

**Comment by xinbenlv** [comment]
Sorry, I didn't actively update this one for a while, I will try to update it as soon as possible

**Comment by honglio** [comment]
API2.0 Should be OK now after the commit - https://github.com/xinbenlv/passport-renren/commit/ec80b6f756fb75a27537fd805a284d83b9bfba22
